version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sudarshan512
      POSTGRES_PASSWORD: sud12345
      POSTGRES_DB: gin_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
